### ISSUE TITLE
Xcode 16.0 build error

### ISSUE THREAD

**Issue by seyfeddin** [admost/AMR-IOS-ADAPTER-MYTARGET#1]
When building with Xcode 16.0 RC, we get the following error. Seems like ADClient is part of Apple's iAd framework.

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_ADClient", referenced from:
       in MyTrackerSDK[62](MRIadHandler.o)

**Comment by erge-akova** [comment]
Networks have started to release updates for Xcode16. When I tested the latest version of MyTarget with Xcode16(16A242d) version for you, this problem seems to be solved. With AMRAdapterMytarget 5.21.8.0 this problem will be solved.
